### ISSUE TITLE
Support for place-items, place-content, place-self

### ISSUE THREAD

**Issue by Dozorengel** [subhero24/tailwindcss-grid-placement#1]
Your plugin is very useful while tailwind is lacking this functionality. However, these 3 properties are missing to provide the complete number of grid properties. I know, that they are just shorthands, but still I am used to them. It would be great to see them in your plugin as well.

**Comment by subhero24** [comment]
Not all property values for align and justify are the same, for example align supports `baseline` and justify supports `left` and `right`. In normal CSS you could do `place-items: baseline left`. So we could generate classes like `place-items-baseline-left` and `place-content-start-end`, but maybe it would make it unnecessarily complex?

I have only ever used the `place-` shortcut for `place-items: center` or `place-content: center`. So maybe it would be enough to add only those 2?

**Comment by Dozorengel** [comment]
I agree, it turns out rather complex. I have no idea how it'd be implemented by Adam, maybe using some shortened forms of properties.
Actually, that's what I meant about these shortcuts. Yep, that would be quite enough, I also don't use these complex `place-` constructions

**Comment by subhero24** [comment]
I decided not to add them, as centering in both directions seems to be the only common use case and the added complexity does not outweigh the benefits, as it is just a shorthand for two of the current classes which are more flexible.
